import Head from "next/head";
import DarkModeToggle from "../components/DarkModeToggle";
import "tailwindcss/tailwind.css";

export default function Home() {
  return (
    // <div className="min-w-screen flex justify-center px-4 py-6 min-h-screen bg-gray-100 dark:bg-gray-400 sm:p-12">
    <div className="w-screen min-h-screen dark:bg-gray-500 bg-white">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute right-4 top-4 sm:right-20">
        <DarkModeToggle />
      </div>
      <div className="mx-auto px-4 py-12 w-full max-w-screen-lg min-h-full sm:p-20">
        <h1 className="dark:text-gray-200 text-gray-400">Hello World</h1>
        <p className="dark:text-gray-200 text-gray-400">
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut eius officia aut deleniti perspiciatis tempore
          velit, quas possimus adipisci sunt magni aspernatur doloremque rerum numquam corrupti deserunt. Consequuntur,
          asperiores fugit.
        </p>
      </div>
    </div>
  );
}
