import Head from "next/head";

export default function Home() {
  return (
    <section>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <h1 className="dark:text-gray-200 text-gray-600">Hello World</h1>
      <p className="dark:text-gray-200 text-gray-600">
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut eius officia aut deleniti perspiciatis tempore
        velit, quas possimus adipisci sunt magni aspernatur doloremque rerum numquam corrupti deserunt. Consequuntur,
        asperiores fugit.
      </p>
    </section>
  );
}
