import Head from "next/head";
import DarkModeToggle from "../components/DarkModeToggle";
import Header from "../components/Header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute right-4 top-4 sm:right-20">
        <DarkModeToggle />
      </div>
      <div className="mx-auto px-4 py-20 w-full max-w-screen-lg sm:p-20">
        <Header />

        <section>
          <h1 className="dark:text-gray-200 text-gray-600">Hello World</h1>
          <p className="dark:text-gray-200 text-gray-600">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Ut eius officia aut deleniti perspiciatis tempore
            velit, quas possimus adipisci sunt magni aspernatur doloremque rerum numquam corrupti deserunt.
            Consequuntur, asperiores fugit.
          </p>
        </section>
      </div>
    </>
  );
}
